### Registra um novo Cliente
POST http://localhost:3000/client
Content-Type: application/json

{
  "login": "luisa",
  "password": "12345"
}

### Lista os Clientes
GET http://localhost:3000/client

### Informações sobre um Cliente por id
GET http://localhost:3000/client/12

### Apaga um Cliente por id
DELETE http://localhost:3000/client/11

### Autenticação (extra, precisa ser incrementado)
POST http://localhost:3000/client/login
Content-Type: application/json

{
  "login": "deco",
  "password": "12345"
}


### Cria uma nova Categoria
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "Camisa"
}

### Lista as Categorias
GET http://localhost:3000/category

### Detalhes de uma Categoria por id
GET http://localhost:3000/category/5

### Apaga uma Categoria (Não pode ter produtos associados)
DELETE http://localhost:3000/category/2


### Cria um Produto
POST http://localhost:3000/product
Content-Type: application/json

{
  "name": "Polo G Vermelha",
  "price": 199.90,
  "categoryId": 7,
  "stock": 4
}

### Lista os Produtos
GET http://localhost:3000/product

### Detalhes de um Produto por id
GET http://localhost:3000/product/6

### Lista de Produtos por categoria
GET http://localhost:3000/product/category/5

### Apaga um Produto por id
DELETE http://localhost:3000/product/5

### Edita um Produto por id
PUT http://localhost:3000/product/6
Content-Type: application/json

{
  "name": "Harry Potter",
  "price": 49.5,
  "categoryId": 5,
  "stock": 10
}


### Cria um Pedido
POST http://localhost:3000/order
Content-Type: application/json

{
  "clientId": 13,
  "items": [
    {
    "productId": 13,
    "amount": 1
    }
  ]
}

### Lista os pedidos
GET http://localhost:3000/order

### Detalha um pedido por id
GET http://localhost:3000/order/3

### Lista pedidos por cliente
GET http://localhost:3000/order/client/13

### Apaga um pedido por id
DELETE http://localhost:3000/order/2


###
GET http://localhost:3000/report/stock

###
GET http://localhost:3000/report/stock/category/5

###
GET http://localhost:3000/report/sold-products?startDate=2024-11-01&endDate=2024-11-04

###
GET http://localhost:3000/report/sells?startDate=2024-11-01&endDate=2024-11-04